package services.operacion.token;

import jakarta.enterprise.context.ApplicationScoped;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

@ApplicationScoped
public class TokenRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        
        rest("/tokens")
            .description("Servicio que obtiene todos los tokens de agentes conversacionales")
            .consumes("application/json")
            .produces("application/json")

            .get()
                .to("direct:getTokens")

            .post()
                .consumes("application/json")
                .produces("application/json")
                .param()
                    .name("name")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("agenteId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("expirationTime")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("minutesToExpire")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("refreshable")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("createdBy")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:createToken")
            
            .put()
                .consumes("application/json")
                .produces("application/json")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("name")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("expirationTime")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("minutesToExpire")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("refreshable")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:updateToken")

            .delete()
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:deleteToken")

            .put("/activate")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:activateToken")

            .put("/deactivate")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:deactivateToken");
        
    }

}
