package services.operacion.token;

import jakarta.enterprise.context.ApplicationScoped;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

@ApplicationScoped
public class TokenRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        
        rest("/tokens")
            .description("Servicio que obtiene todos los tokens de agentes conversacionales")
            .consumes("application/json")
            .produces("application/json")

            .get()
                .to("direct:getTokens")

            .get("/{tokenId}")
                .param().name("tokenId")
                    .type(RestParamType.path)
                    .required(true)
                    .description("Id del token")
                .endParam()
                .to("direct:getTokensById")

            .post()
                .consumes("application/json")
                .produces("application/json")
                .param()
                    .name("name")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam() 
                .param()
                    .name("expirationTime")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("minutesToExpire")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("refreshable")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("createdBy")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:createToken")
            
            .put()
                .consumes("application/json")
                .produces("application/json")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("name")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("expirationTime")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("minutesToExpire")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("refreshable")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:updateToken")

            .delete()
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:deleteToken")
 

            .put("/status")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("status")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:changeStatusToken")

            .post("/agente")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("agentId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:addAgentToToken")

            .post("/delete/agente")
                .param()
                    .name("tokenId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .dataType("string")
                    .required(true)
                .endParam()
                .param()
                    .name("agentId")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(true)
                .endParam()
                .to("direct:removeAgentFromToken");
        
    }

}
